assets_path = "./assets/"
fonts_path = assets_path + "fonts/"
images_path = assets_path + "images/"
images_cryptocurrencies_path = images_path + "cryptocurrencies/"
images_stickers_path = images_path + "stickers/"
images_templates_path = images_path + "templates/"
